name: "Tests"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get message
        id: get_authors
        uses: ./
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Echo
        shell: bash -ex {0}
        run: |
          echo "${{ steps.get_authors.outputs.* }}"

      - name: Slack Release notification
        env:
          MESSAGE: ${{ steps.get_authors.outputs.message }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOYS_WEBHOOK }}
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: |-
            {{ MESSAGE }}
